[package]
edition = "2024"
name = "metroferris_derive"
version = "0.1.1"
authors = ["Varazdat Stepanyan"]
description = "A kinetic monte carlo (and beyond) engine designed for scientific computing"
readme = "README.md"
repository = "https://github.com/VarazdatStepanyan003/"
license = "GPL-3.0-only"
keywords = ["scientific", "simulation"]
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
